// examples/react/PrayerTimesWidget.jsx
import { useEffect } from "react";

const widgetUrl =
  "https://cdn.jsdelivr.net/gh/PrayerZone/prayer-times-widget@v2.0.1/src/prayer-zone-widget.js";

let widgetPromise;

function loadWidget() {
  widgetPromise ??= import(/* @vite-ignore */ widgetUrl);
  return widgetPromise;
}

export function PrayerTimesWidget({
  city = "paris",
  language = "en",
  theme = "auto",
  compact = false,
  showQibla = true,
}) {
  useEffect(() => {
    void loadWidget();
  }, []);

  return (
    <prayer-zone-widget
      city={city}
      lang={language}
      theme={theme}
      compact={compact ? "" : undefined}
      show-qibla={showQibla ? "" : undefined}
    />
  );
}

// examples/svelte/PrayerTimesWidget.svelte
<script>
  import { onMount } from "svelte";

  export let city = "paris";
  export let language = "en";
  export let theme = "auto";
  export let showQibla = true;

  onMount(() => {
    void import(
      /* @vite-ignore */
      "https://cdn.jsdelivr.net/gh/PrayerZone/prayer-times-widget@v2.0.1/src/prayer-zone-widget.js"
    );
  });
</script>

<prayer-zone-widget
  {city}
  lang={language}
  {theme}
  show-qibla={showQibla ? "" : undefined}
/>
