// examples/svelte/PrayerTimesWidget.svelte
<script>
  import { onMount } from "svelte";

  export let city = "paris";
  export let language = "en";
  export let theme = "auto";
  export let showQibla = true;

  onMount(() => {
    void import(
      /* @vite-ignore */
      "https://cdn.jsdelivr.net/gh/PrayerZone/prayer-times-widget@v2.0.1/src/prayer-zone-widget.js"
    );
  });
</script>

<prayer-zone-widget
  {city}
  lang={language}
  {theme}
  show-qibla={showQibla ? "" : undefined}
/>

// examples/nextjs/PrayerTimesWidget.jsx
"use client";

import { useEffect } from "react";

const widgetUrl =
  "https://cdn.jsdelivr.net/gh/PrayerZone/prayer-times-widget@v2.0.1/src/prayer-zone-widget.js";

let widgetPromise;

export function PrayerTimesWidget({
  city = "paris",
  language = "en",
  theme = "auto",
}) {
  useEffect(() => {
    widgetPromise ??= import(/* webpackIgnore: true */ widgetUrl);
    void widgetPromise;
  }, []);

  return (
    <prayer-zone-widget
      city={city}
      lang={language}
      theme={theme}
      show-qibla=""
    />
  );
}
